### ISSUE TITLE
Reset location permissions bug

### ISSUE THREAD

**Issue by 0xPetra** [zkMaps/client#29]

**Comment by 0xPetra** [comment]
1/ Reset location permissions
2/ Refresh page
3/ Accept location permissions
4/ Click on "RayTracing4 - New Zealand"

Then the whole page goes grey and you get this error.
![image](https://user-images.githubusercontent.com/20055787/183266778-8441b32c-e213-4796-8944-b4e77c139a31.png)

Here's the error message: 
```
dispatchRequest.js:216 Error: Invalid LatLng object: (undefined, undefined)
    at new U (LatLng.js:32:9)
    at F (LatLng.js:123:11)
    at t.initialize (Marker.js:112:18)
    at new t (Class.js:24:20)
    at DecadeBody.js:4:20
    at slot.ts:16:35
```
    at generic.js:22:28
    at t (events.js:6:41)
    at sa (dispatchRequest.js:157:137)
    at za (dispatchRequest.js:176:260)
